### ISSUE TITLE
Templates in Meetings and Events Folder

### ISSUE THREAD

**Issue by macmccammon** [ghwood/www.ietf.org#11]
## URL

http://www7.ietf.org/admin/pages/30/
## Expected Behavior

I should be able to add a child page and select from the template list for that page.
## Actual Behavior

It is defaulting to an event page template. The list does not show up. 
## Reproducing
- Browser: Chrome 
- OS: 10.9.4 
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
This is expected behavior. By default, Event page templates are created for child pages of Event Index page. To have a non-event page template as a Child of an Event index, you must first create the page elsewhere on the site and then move it to the the Childe location. We can ask that all templates be available as a choice of the Event Index page. I have flagged this as a feature request.

**Comment by ghwood** [comment]
This has been fixed.
