### ISSUE TITLE
IESG minutes parent page causes 404 error

### ISSUE THREAD

**Issue by cindymorgan** [ghwood/www.ietf.org#71]
## URL

https://beta.ietf.org/about/groups/iesg/iesg-meeting-minutes/

## Expected Behavior

This should look like what is at https://beta.ietf.org/about/groups/iesg/minutes/ (the page linked from the main IESG page)

https://beta.ietf.org/about/groups/iesg/iesg-meeting-minutes/ is listed as the parent page for all of the minutes by year index pages (e.g. https://beta.ietf.org/about/groups/iesg/iesg-meeting-minutes/iesg-minutes-2016/) 

## Actual Behavior

A 404 error

## Reproducing

- Browser: Firefox 54.0.1
- OS: MacOS 10.10.5
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
Hi Cindy,
Sorry for the delay in responding. 

It turns out the parent page at: 

https://beta.ietf.org/about/groups/iesg/iesg-meeting-minutes/
- this page has children for minutes through 2017.

BUT It is only a "draft" which is why it was returning a 404.

The page at:

https://beta.ietf.org/about/groups/iesg/minutes/
- this page has children for minutes through 2016.

is "live" and linked.

So, there seem to be 2 home pages for IESG minutes. Not sure how that happened or how you'd like to resolve at this point. Perhaps a short phone conversation would sort this quickly? Let me know.

-Greg

**Comment by ghwood** [comment]
Cindy,

I took a few minutes and "fixed" the minutes, but it would be good to double check in a quick conversation. 

There are also some questions about the how to structure the IESG section (such as what should appear in the right side menu) that would be great to sort out.

Let me know if you have time to chat briefly and/or if someone else should be in the loop.

-Greg

**Comment by ghwood** [comment]
The minutes issue is fixed so closing the tickets. Now at: https://beta.ietf.org/about/groups/iesg/minutes/
